### ISSUE TITLE
Is there any way to clear a dropdown filed as setAttributeValue dose not clear the UI

### ISSUE THREAD

**Issue by x8Haider** [danvick/flutter_form_builder#130]
Hello,

I'm trying to clear / reset a dropdown field by using setAttributeValue, but it does not change in UI, further more I can't clear the dropdown value as I can't use controller attribute. 
My issue is I have to tow linked dropdown fields and while the user select a value from the second dropdown and then change the first dropdown  I got following issue:

════════ Exception Caught By widgets library ═════════════════════════════════════
The following assertion was thrown building FormField<dynamic>-[LabeledGlobalKey<FormFieldState<dynamic>>#11791](dirty, dependencies: [_FormScope], state: FormFieldState<dynamic>#4e075):
'package:flutter/src/material/dropdown.dart': Failed assertion: line 608 pos 15: 'items == null || items.isEmpty || value == null || items.where((DropdownMenuItem<T> item) => item.value == value).length == 1': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      new DropdownButton (package:flutter/src/material/dropdown.dart:608:15)
#3      _FormBuilderDropdownState.build.<anonymous closure> (package:flutter_form_builder/src/fields/form_builder_dropdown.dart:104:20)
#4      FormFieldState.build (package:flutter/src/widgets/form.dart)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
...
═══════════════════════════════════════════════════════════
 I understand this is Material dropdown library issue, but I figure out if I reset the form just after I return the list from the API based on first dropdown value the issue is not there.. but this does not the solution for it as on every change on first dropdown it will reset every thing.

I saw one of the issues and the workaround was to add controller  but can't do the same in FormBuilderDropdown.

Please help me. 

Thanks in advance.

**Comment by x8Haider** [comment]
Support Sucks here!!! Closing... for no support!
