### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by knarfamlap** [danvick/flutter_form_builder#315]
Hello!

I am migrating my app to web. To use flutter's web support I have to be within the flutter beta channel.

When I attempt to host the local server, I get this compiler error: 

```code
                    Compiler message:
[        ]
../../.pub-cache/hosted/pub.dartlang.org/flutter_chips_inpu
t-1.8.1/lib/src/chips_input.dart:65:7: Error: The
non-abstract class 'ChipsInputState' is missing
implementations for these members:
[        ]  - TextInputClient.currentAutofillScope
[        ] Try to either
[        ]  - provide an implementation,
[        ]  - inherit an implementation from a superclass
or mixin,
[        ]  - mark the class as abstract, or
[        ]  - provide a 'noSuchMethod' implementation.
[        ] class ChipsInputState<T> extends
State<ChipsInput<T>>
[        ]       ^^^^^^^^^^^^^^^
[        ]
../../development/flutter/packages/flutter/lib/src/services
/text_input.dart:769:21: Context:
'TextInputClient.currentAutofillScope' is defined here.
[        ]   AutofillScope get currentAutofillScope;
[        ]                     ^^^^^^^^^^^^^^^^^^^^
[+11731 ms] Syncing files to device Web Server...
(completed in 13,049ms, longer than expected)
[        ] Synced 0.0MB.
[        ] Failed to compile application.
[   +3 ms] "flutter run" took 18,349ms.

#0      throwToolExit
(package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand
(package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:797:
18)
#3      _rootRunUnary (dart:async/zone.dart:1198:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#5      _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
#6      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
#7      Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
#8      Future._completeWithValue
(dart:async/future_impl.dart:529:5)
#9      _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
#10     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
#11     RunCommand.usageValues
(package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
#18     Future._asyncCompleteWithValue.<anonymous closure>
(dart:async/future_impl.dart:567:7)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:1037:23)
#23     _microtaskLoop
(dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop
(dart:async/schedule_microtask.dart:50:5)
#25     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)
```

I realized that flutter form builder has flutter chips input as a dependency. So I went ahead and removed all the code that has a reference to flutter form builder and it successfully ran. Is there any work around to this?

Thanks in advanced!

**Comment by danvick** [comment]
Kindly find the solution to this problem [here](https://github.com/danvick/flutter_chips_input/issues/37#issuecomment-618948172).

You'll need to add the dev version of chips_input to your `pubspec.yaml` to override the one that comes the package.
