### ISSUE TITLE
Cut & Paste trigger Exception with Typeahead

### ISSUE THREAD

**Issue by awhitford** [danvick/flutter_form_builder#347]
A **Cut** or **Paste** into a **FormBuilderTypeAhead** triggers an exception: 
```
Tried calling: call("pasted_text")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      new TypeAheadFormField.<anonymous closure>.<anonymous closure> (package:flutter_typeahead/flutter_typeahead.dart:315:53)
#2      EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:1691:23)
#3      EditableTextState.textEditingValue= (package:flutter/src/widgets/editable_text.dart:1842:5)
#4      TextSelectionControls.handlePaste (package:flutter/src/widgets/text_selection.dart:228:16)
#5      _rootRunUnary (dart:async/zone.dart:1192:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async<…>
```
This seems like a [known issue with `flutter_typeahead`](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/185).

https://github.com/AbdulRahmanAlHamali/flutter_typeahead/blob/398aa83b7d3607131921153e50ee879651c44d4d/lib/flutter_typeahead.dart#L315

Adding `onChanged: (_){}` does NOT solve this because `FormBuilderTypeAhead` does not propagate this to `TypeAheadFormField`:

https://github.com/danvick/flutter_form_builder/blob/3be8176931e15dbf5c998c8a31e9df8bd4b2fc66/lib/src/fields/form_builder_typeahead.dart#L132

**Comment by awhitford** [comment]
I just realized that this issue is purely a `flutter_typeahead` issue and there is no way for `flutter_form_builder` to resolve it.
