### ISSUE TITLE
Error: Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by zsoerenm** [danvick/flutter_form_builder#583]
This error happens with the current example app.
Steps to reproduce:
1. Add a chip to "chips" e.g. "Paul"
2. Select "Female" in "Gender"

The order is important. If something else is selected or clicked in between, the error won't show up.

This is the complete error:
```
The following assertion was thrown while dispatching notifications for FocusNode:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
package:flutter/…/widgets/framework.dart:3906
#1      Element._debugCheckStateIsActiveForAncestorLookup
package:flutter/…/widgets/framework.dart:3920
#2      Element.findAncestorStateOfType
package:flutter/…/widgets/framework.dart:4039
#3      Overlay.of
package:flutter/…/widgets/overlay.dart:258
#4      SuggestionsBoxController.open
package:flutter_chips_input/src/suggestions_box_controller.dart:17
...
The FocusNode sending notification was: FocusNode#275d6([PRIMARY FOCUS])
    PRIMARY FOCUS
════════════════════════════════════════════════════════════════════════════════
E/flutter ( 4080): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'findRenderObject' was called on null.
E/flutter ( 4080): Receiver: null
E/flutter ( 4080): Tried calling: findRenderObject()
E/flutter ( 4080): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 4080): #1      ChipsInputState._openInputConnection.<anonymous closure>.<anonymous closure>
package:flutter_chips_input/src/chips_input.dart:268
E/flutter ( 4080): #2      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1117
E/flutter ( 4080): #3      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1063
E/flutter ( 4080): #4      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:971
E/flutter ( 4080): #5      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 4080): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 4080): #7      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 4080): #8      _invoke (dart:ui/hooks.dart:251:10)
E/flutter ( 4080): #9      _drawFrame (dart:ui/hooks.dart:209:3)
```
Flutter version:
```
Flutter is already up to date on channel stable
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (9 days ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4
```

**Comment by zsoerenm** [comment]
This error seems similar to https://github.com/danvick/flutter_form_builder/issues/572.

**Comment by danielweil** [comment]
I am getting this error when I use the TypeAhead widget.

![image](https://user-images.githubusercontent.com/44274213/100157540-7bf54180-2e89-11eb-9cc7-76211bd3dc5d.png)

**Comment by awhitford** [comment]
@zsoerenm Can you please do a `flutter pub upgrade` and confirm if this is still a problem?  (There was a bug fix made to `flutter_chips_input` that may have solved this.)

**Comment by awhitford** [comment]
I am unable to reproduce this error with the latest code.

I do see a _Network Image_ exception because `https://mbtskoudsalg.com/images/person-stock-image-png.png` is invalid.  However, I am unable to replicate the _Focus Node_ exception.  I suspect the root issue has been fixed.

**Comment by danielweil** [comment]
Will have a look into it!

**Comment by danielweil** [comment]
Have a question, doubt, I don't have flutter_chips_input as a direct dependency. Only flutter_form_builder. I am able to use this new version without having a new Form Builder release? Or do I have to use dev branch?

**Comment by danvick** [comment]
For now, you could use `dependency_overrides`.

**Comment by awhitford** [comment]
@danielweil A `flutter pub upgrade` will upgrade the `flutter_chips_input` transitive dependency (because `1.9.5` is a minor upgrade to `^1.9.4`, declared by `flutter_form_builder`).

**Comment by zsoerenm** [comment]
@awhitford thank you for taking your time to have a look at this issue! 
I was not able to use the newest version (4.0.2) of flutter_form_builder, due to this build error: https://github.com/danvick/flutter_form_builder/issues/629
So I downgraded to v3.14.1 using git and specified flutter_chips_input: ^1.9.5 in pubspec.yaml
However, the error still persist. If you follow the above steps, the following error will occur:
```
E/flutter (10874): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: A FocusNode was used after being disposed.
E/flutter (10874): Once you have called dispose() on a FocusNode, it can no longer be used.
E/flutter (10874): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
package:flutter/…/foundation/change_notifier.dart:117
E/flutter (10874): #1      ChangeNotifier._debugAssertNotDisposed
package:flutter/…/foundation/change_notifier.dart:123
E/flutter (10874): #2      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:234
E/flutter (10874): #3      FocusNode._notify
package:flutter/…/widgets/focus_manager.dart:1050
E/flutter (10874): #4      FocusManager._applyFocusChange
package:flutter/…/widgets/focus_manager.dart:1769
E/flutter (10874): #5      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (10874): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (10874): #7      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (10874): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (10874): #9      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (10874): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (10874): #11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (10874): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (10874): #13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (10874): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
```
> flutter pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name     Current  Upgradable  Resolvable  Latest  

direct dependencies: all up-to-date.

transitive dependencies:
asn1lib          *0.6.5   *0.6.5      *0.6.5      0.8.1   
json_annotation  *3.0.1   *3.0.1      *3.0.1      3.1.1   
phone_number     *0.6.3   *0.6.3      *0.6.3      0.8.1   
pointycastle     *1.0.2   *1.0.2      *1.0.2      2.0.0   
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.
```
```
> flutter --version                                                                                           ✔ 
Flutter 1.24.0-10.2.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 022b333a08 (vor 3 Wochen) • 2020-11-18 11:35:09 -0800
Engine • revision 07c1eed46b
Tools • Dart 2.12.0 (build 2.12.0-29.10.beta)
```

**Comment by awhitford** [comment]
We need to get you working on the version 4 track because I'm sure this issue has been fixed. I'll take a closer look at #629. 

Are you not using Stable channel?  Which channel?

**Comment by zsoerenm** [comment]
I switched from dev to stable channel and indeed the error is gone. I am sorry for the hassle. 
Thank you for fixing it!
