### ISSUE TITLE
FormBuilderSearchableDropdown error when inputing text

### ISSUE THREAD

**Issue by nicks258** [danvick/flutter_form_builder#971]
Facing issue when I started typing in **FormBuilderSearchableDropdown**. Throwing error - 
`======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder(dirty):
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

The relevant error-causing widget was: 
  GetMaterialApp GetMaterialApp:file:///C:/Users/Others/AndroidStudioProjects/flutter-starter/lib/main.dart:56:14
When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4153:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4167:6)
#2      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4252:12)
#3      InheritedTheme.capture (package:flutter/src/widgets/inherited_theme.dart:102:10)
#4      InheritedTheme.captureAll (package:flutter/src/widgets/inherited_theme.dart:67:12)
#5      _PopupMenuRoute.buildPage (package:dropdown_search/src/popupMenu.dart:473:29)
#6      _ModalScopeState.build.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/routes.dart:872:55)
#7      Builder.build (package:flutter/src/widgets/basic.dart:7398:48)
====================================================================================================`
I am using following dependencies
flutter_form_builder: ^7.1.1
form_builder_extra_fields: ^7.1.0
 form_builder_validators: ^7.6.1.
Looking for quick help. Thanks(; @danvick @tjarvstrand

**Comment by nicks258** [comment]
Any update???

**Comment by hungtrn75** [comment]
Same issue. Can anyone help me?
